import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  // Core tables
  cases: defineTable({
    masterId: v.optional(v.string()),
    status: v.optional(v.string()),
    clientName: v.optional(v.string()),
    clientPhone: v.optional(v.string()),
    clientEmail: v.optional(v.string()),
    carrier: v.optional(v.string()),
    claimType: v.optional(v.string()),
    vehicleYear: v.optional(v.number()),
    vehicleMake: v.optional(v.string()),
    vehicleModel: v.optional(v.string()),
    vehicleVin: v.optional(v.string()),
    vehicleMileage: v.optional(v.number()),
    insuranceEstimate: v.optional(v.string()),
    dateOfLoss: v.optional(v.string()),
    notes: v.optional(v.string()),
    source: v.optional(v.string()),
    createdAt: v.optional(v.string()),
    updatedAt: v.optional(v.string()),
    // Extended fields used by cases.ts
    masterCaseId: v.optional(v.string()),
    isProspect: v.optional(v.boolean()),
    prospectId: v.optional(v.string()),
    clientLastName: v.optional(v.string()),
    role: v.optional(v.string()),
    division: v.optional(v.string()),
    incidentDate: v.optional(v.string()),
    openedAt: v.optional(v.number()),
    closedAt: v.optional(v.number()),
    folderName: v.optional(v.string()),
    ghlContactId: v.optional(v.string()),
  }).index('by_status', ['status']),

  tasks: defineTable({
    id: v.optional(v.string()),
    type: v.optional(v.string()),
    payload: v.optional(v.any()),
    status: v.union(v.literal('queued'), v.literal('running'), v.literal('success'), v.literal('error'), v.literal('todo'), v.literal('in_progress'), v.literal('review'), v.literal('done')),
    createdAt: v.optional(v.union(v.string(), v.number())),
    workerId: v.optional(v.string()),
    startedAt: v.optional(v.union(v.string(), v.number())),
    completedAt: v.optional(v.union(v.string(), v.number())),
    result: v.optional(v.string()),
    error: v.optional(v.string()),
    // Extended fields used by tasks page
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    priority: v.optional(v.string()),
    assignee: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    updatedAt: v.optional(v.number()),
    dueDate: v.optional(v.string()),
    claimId: v.optional(v.string()),
    content: v.optional(v.string()),
  }).index('by_status', ['status']),

  activity: defineTable({
    agentName: v.string(),
    action: v.string(),
    details: v.optional(v.string()),
    type: v.union(v.literal("task"), v.literal("memory"), v.literal("agent"), v.literal("system"), v.literal("api"), v.literal("document")),
    createdAt: v.number(),
  }).index('by_created', ['createdAt']),

  agents: defineTable({
    name: v.string(),
    role: v.string(),
    type: v.union(v.literal("primary"), v.literal("sub-agent")),
    status: v.union(v.literal("active"), v.literal("idle"), v.literal("working"), v.literal("offline")),
    responsibilities: v.array(v.string()),
    emoji: v.string(),
    pixelColor: v.optional(v.string()),
    currentTask: v.optional(v.string()),
    tasksCompleted: v.number(),
    createdAt: v.number(),
  }),

  awardRequests: defineTable({
    claimId: v.optional(v.string()),
    claimNumber: v.optional(v.string()),
    ownerName: v.optional(v.string()),
    carrier: v.optional(v.string()),
    vehicle: v.optional(v.string()),
    vin: v.optional(v.string()),
    acvAward: v.number(),
    insuredAppraiser: v.optional(v.string()),
    insurerAppraiser: v.optional(v.string()),
    umpire: v.optional(v.string()),
    dateOfLoss: v.optional(v.string()),
    awardDate: v.optional(v.string()),
    status: v.string(),
    sigPageToken: v.string(),
    insuredSigDate: v.optional(v.string()),
    insurerSigDate: v.optional(v.string()),
    umpireSigDate: v.optional(v.string()),
  }).index('by_token', ['sigPageToken']).index('by_claim', ['claimId']),

  calendar: defineTable({
    title: v.string(),
    description: v.optional(v.string()),
    type: v.union(v.literal("task"), v.literal("cron"), v.literal("event")),
    scheduledAt: v.number(),
    cronExpression: v.optional(v.string()),
    status: v.union(v.literal("scheduled"), v.literal("running"), v.literal("completed"), v.literal("failed")),
    assignee: v.string(),
    createdAt: v.number(),
  }),

  caseAttachments: defineTable({
    claimId: v.string(),
    section: v.string(),
    fileName: v.string(),
    mimeType: v.string(),
    storageId: v.string(),
    sizeBytes: v.optional(v.number()),
    uploadedAt: v.number(),
  }).index('by_claim', ['claimId']),

  caseRegistry: defineTable({
    masterId: v.optional(v.string()),
    caseKey: v.string(),
    driveFolderId: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    // Extended fields used by cases page
    clientName: v.optional(v.string()),
    carrier: v.optional(v.string()),
    status: v.optional(v.string()),
    role: v.optional(v.string()),
    openedAt: v.optional(v.number()),
    contactId: v.optional(v.string()),
    division: v.optional(v.string()),
    opportunityId: v.optional(v.string()),
    notes: v.optional(v.string()),
    // Extended fields used by caseRegistry.ts
    masterCaseId: v.optional(v.string()),
    year: v.optional(v.string()),
    lastName: v.optional(v.string()),
    updatedAt: v.optional(v.number()),
    happyCustomer: v.optional(v.boolean()),
    billingType: v.optional(v.string()),
    hourlyRate: v.optional(v.number()),
    driveFolder: v.optional(v.string()),
  }).index('by_masterCaseId', ['masterCaseId'])
    .index('by_contact', ['contactId']),

  aiUsageLogs: defineTable({
    ts: v.number(),
    provider: v.string(),
    model: v.string(),
    agentName: v.string(),
    route: v.string(),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    estCostUsd: v.optional(v.number()),
    durationMs: v.optional(v.number()),
    success: v.boolean(),
  }).index('by_ts', ['ts']),

  claims: defineTable({
    ghlId: v.optional(v.string()),
    masterId: v.optional(v.string()),
    status: v.optional(v.string()),
    clientName: v.string(),
    carrier: v.optional(v.string()),
    claimType: v.optional(v.string()),
    daysOpen: v.optional(v.number()),
    nextAction: v.optional(v.string()),
    priority: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    // Extended fields used by claims page
    stage: v.optional(v.string()),
    openingOffer: v.optional(v.number()),
    settlementAmount: v.optional(v.number()),
    year: v.optional(v.union(v.string(), v.number())),
    make: v.optional(v.string()),
    model: v.optional(v.string()),
    insurer: v.optional(v.string()),
    // Extended fields used by claims.ts and ghl.ts
    openedAt: v.optional(v.number()),
    settledAt: v.optional(v.number()),
    closedAt: v.optional(v.number()),
    targetValue: v.optional(v.number()),
    outcome: v.optional(v.string()),
    assignedAgent: v.optional(v.string()),
    vin: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    documents: v.optional(v.any()),
    notes: v.optional(v.string()),
    // GHL extended fields
    ghlContactId: v.optional(v.string()),
    ghlOpportunityId: v.optional(v.string()),
    ghlPipelineId: v.optional(v.string()),
    ghlStageId: v.optional(v.string()),
    phone: v.optional(v.string()),
    email: v.optional(v.string()),
    address1: v.optional(v.string()),
    city: v.optional(v.string()),
    state: v.optional(v.string()),
    postalCode: v.optional(v.string()),
    trim: v.optional(v.string()),
    mileage: v.optional(v.number()),
    adjusterName: v.optional(v.string()),
    adjusterPhone: v.optional(v.string()),
    adjusterEmail: v.optional(v.string()),
  }).index('by_status', ['status'])
    .index('by_ghl_contact', ['ghlContactId'])
    .searchIndex('search_claims', { searchField: 'clientName' }),

  caseAnalysisReport: defineTable({
    allCases: v.optional(v.any()),
    summary: v.optional(v.any()),
    generatedAt: v.number(),
    // Extended fields used by analyzeAllCases.ts
    reportDate: v.optional(v.string()),
    totalCasesAnalyzed: v.optional(v.number()),
    stalledCases: v.optional(v.any()),
    highVarianceComps: v.optional(v.any()),
    settlementTrends: v.optional(v.any()),
    outliers: v.optional(v.any()),
    createdAt: v.optional(v.number()),
  }),

  content: defineTable({
    type: v.optional(v.string()),
    title: v.string(),
    body: v.optional(v.string()),
    createdAt: v.number(),
    publishedAt: v.optional(v.number()),
    // Extended fields used by content page
    stage: v.optional(v.string()),
    description: v.optional(v.string()),
    trendScore: v.optional(v.number()),
    // Extended fields used by content.ts
    script: v.optional(v.string()),
    platform: v.optional(v.array(v.string())),
    sourceUrl: v.optional(v.string()),
    updatedAt: v.optional(v.number()),
    tags: v.optional(v.array(v.string())),
    notes: v.optional(v.string()),
  }),

  documents: defineTable({
    caseId: v.optional(v.string()),
    type: v.optional(v.string()),
    fileName: v.optional(v.string()),
    storageId: v.optional(v.string()),
    createdAt: v.number(),
    // Extended fields used by documents.ts
    title: v.optional(v.string()),
    content: v.optional(v.string()),
    category: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    clientName: v.optional(v.string()),
    fileType: v.optional(v.string()),
    updatedAt: v.optional(v.number()),
  }).searchIndex('search_documents', { searchField: 'content' }),

  expenseEntries: defineTable({
    caseId: v.string(),
    description: v.string(),
    amount: v.number(),
    date: v.string(),
    createdAt: v.number(),
    category: v.optional(v.string()),
    billable: v.optional(v.boolean()),
    receipt: v.optional(v.string()),
    source: v.optional(v.string()),
    emailRef: v.optional(v.string()),
    approved: v.optional(v.boolean()),
  }).index('by_case', ['caseId']),

  files: defineTable({
    fileName: v.string(),
    storageId: v.optional(v.string()),
    mimeType: v.optional(v.string()),
    sizeBytes: v.optional(v.number()),
    uploadedAt: v.optional(v.number()),
    // Extended fields used by files.ts
    name: v.optional(v.string()),
    category: v.optional(v.string()),
    driveUrl: v.optional(v.string()),
    localPath: v.optional(v.string()),
    clientName: v.optional(v.string()),
    claimId: v.optional(v.string()),
    recordingId: v.optional(v.string()),
    notes: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    uploadedBy: v.optional(v.string()),
    createdAt: v.optional(v.number()),
  }).searchIndex('search_files', { searchField: 'name' }),

  ghlCalendarEvents: defineTable({
    ghlEventId: v.optional(v.string()),
    title: v.string(),
    startTime: v.number(),
    endTime: v.number(),
    attendees: v.optional(v.array(v.string())),
    syncedAt: v.optional(v.number()),
    appointmentStatus: v.optional(v.string()),
    status: v.optional(v.string()),
    calendarId: v.optional(v.string()),
    calendarName: v.optional(v.string()),
    contactName: v.optional(v.string()),
    // Extended fields used by ghlCalendar.ts
    eventId: v.optional(v.string()),
    contactId: v.optional(v.string()),
    locationId: v.optional(v.string()),
    notes: v.optional(v.string()),
    updatedAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index('by_event_id', ['eventId'])
    .index('by_start_time', ['startTime'])
    .index('by_calendar_id', ['calendarId']),

  memories: defineTable({
    agentName: v.optional(v.string()),
    content: v.string(),
    createdAt: v.number(),
    // Extended fields used by memories.ts
    title: v.optional(v.string()),
    type: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    clientName: v.optional(v.string()),
    source: v.optional(v.string()),
    sourceId: v.optional(v.string()),
    recordedAt: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
  }).searchIndex('search_memories', { searchField: 'content' }),

  negotiationTasks: defineTable({
    caseId: v.optional(v.string()),
    status: v.string(),
    description: v.optional(v.string()),
    assignedTo: v.optional(v.string()),
    createdAt: v.number(),
    // Extended fields used by negotiationTasks.ts
    claimId: v.optional(v.string()),
    clientName: v.optional(v.string()),
    vehicleStr: v.optional(v.string()),
    ourACV: v.optional(v.number()),
    oaACV: v.optional(v.number()),
    gap: v.optional(v.number()),
    oaRawText: v.optional(v.string()),
    oaComps: v.optional(v.any()),
    anchorFlags: v.optional(v.any()),
    analysis: v.optional(v.string()),
    draftRebuttal: v.optional(v.string()),
    ghlContactId: v.optional(v.string()),
    ghlThreadId: v.optional(v.string()),
    updatedAt: v.optional(v.number()),
    sentAt: v.optional(v.number()),
  }).index('by_claim', ['claimId']),

  projects: defineTable({
    name: v.string(),
    status: v.string(),
    description: v.optional(v.string()),
    createdAt: v.number(),
    // Extended fields used by projects.ts
    priority: v.optional(v.string()),
    emoji: v.optional(v.string()),
    progress: v.optional(v.number()),
    owner: v.optional(v.string()),
    nextActions: v.optional(v.array(v.string())),
    updatedAt: v.optional(v.number()),
  }),

  recordings: defineTable({
    fileName: v.optional(v.string()),
    storageId: v.optional(v.string()),
    duration: v.optional(v.number()),
    uploadedAt: v.optional(v.number()),
    // Extended fields used by recordings module
    source: v.optional(v.string()),
    externalId: v.optional(v.string()),
    title: v.optional(v.string()),
    transcript: v.optional(v.string()),
    summary: v.optional(v.string()),
    clientName: v.optional(v.string()),
    claimId: v.optional(v.string()),
    driveUrl: v.optional(v.string()),
    audioUrl: v.optional(v.string()),
    speakers: v.optional(v.array(v.string())),
    tags: v.optional(v.array(v.string())),
    category: v.optional(v.string()),
    recordedAt: v.optional(v.number()),
    notes: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    processed: v.optional(v.boolean()),
  }).searchIndex('search_recordings', { searchField: 'transcript' }),

  settings: defineTable({
    key: v.string(),
    value: v.any(),
    updatedAt: v.number(),
  }).index('by_key', ['key']),

  systemHealth: defineTable({
    status: v.optional(v.string()),
    checkedAt: v.optional(v.number()),
    details: v.optional(v.any()),
    // Extended fields used by systemHealth module
    key: v.optional(v.string()),
    history: v.optional(v.string()),
    ts: v.optional(v.number()),
    cpu: v.optional(v.number()),
    memUsedGb: v.optional(v.number()),
    memTotalGb: v.optional(v.number()),
    memPct: v.optional(v.number()),
    gpuDevice: v.optional(v.number()),
    gpuRenderer: v.optional(v.number()),
    gpuTiler: v.optional(v.number()),
    diskUsedGb: v.optional(v.number()),
    diskTotalGb: v.optional(v.number()),
    diskPct: v.optional(v.number()),
    ollamaModels: v.optional(v.array(v.string())),
    memDevUsedGb: v.optional(v.number()),
    memDevPct: v.optional(v.number()),
    memDevTs: v.optional(v.number()),
    memOllamaUsedGb: v.optional(v.number()),
    memOllamaPct: v.optional(v.number()),
    memOllamaTs: v.optional(v.number()),
    mcDevOnline: v.optional(v.boolean()),
    mcOllamaOnline: v.optional(v.boolean()),
    nodesJson: v.optional(v.string()),
  }).index('by_key', ['key']),

  timeEntries: defineTable({
    caseId: v.string(),
    description: v.string(),
    hours: v.number(),
    date: v.string(),
    createdAt: v.number(),
    category: v.optional(v.string()),
    billable: v.optional(v.boolean()),
    rate: v.optional(v.number()),
    source: v.optional(v.string()),
    emailRef: v.optional(v.string()),
    approved: v.optional(v.boolean()),
  }).index('by_case', ['caseId']),

  valuations: defineTable({
    caseId: v.optional(v.string()),
    vehicleInfo: v.optional(v.any()),
    acvEstimate: v.optional(v.number()),
    source: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
    // Extended fields used by valuations module
    claimId: v.optional(v.string()),
    claimType: v.optional(v.string()),
    lockedAt: v.optional(v.number()),
    insurerOffer: v.optional(v.number()),
    jdPowerValue: v.optional(v.number()),
    kbbValue: v.optional(v.number()),
    comps: v.optional(v.array(v.object({
      source: v.string(),
      description: v.string(),
      price: v.number(),
      mileage: v.optional(v.number()),
      url: v.optional(v.string()),
    }))),
    conditionAdjPct: v.optional(v.number()),
    mileageAdjPct: v.optional(v.number()),
    regionalAdjPct: v.optional(v.number()),
    calculatedACV: v.optional(v.number()),
    acvGap: v.optional(v.number()),
    preLossValue: v.optional(v.number()),
    repairCost: v.optional(v.number()),
    postRepairValue: v.optional(v.number()),
    repairQuality: v.optional(v.union(v.literal("excellent"), v.literal("acceptable"), v.literal("substandard"), v.literal("poor"))),
    structuralDamage: v.optional(v.boolean()),
    airbagDeployment: v.optional(v.boolean()),
    dvMethodology: v.optional(v.string()),
    calculatedDV: v.optional(v.number()),
    insurerDVOffer: v.optional(v.number()),
    dvGap: v.optional(v.number()),
    notes: v.optional(v.string()),
    workbenchData: v.optional(v.string()),
  }),

  clientMemory: defineTable({
    clientName: v.optional(v.string()),
    content: v.optional(v.string()),
    createdAt: v.optional(v.number()),
    // Extended fields used by clientMemory.ts
    caseId: v.optional(v.string()),
    caseKey: v.optional(v.string()),
    contactId: v.optional(v.string()),
    category: v.optional(v.string()),
    text: v.optional(v.string()),
    source: v.optional(v.string()),
    embedding: v.optional(v.array(v.float64())),
    agentId: v.optional(v.string()),
    ts: v.optional(v.number()),
  }).index('by_case', ['caseId'])
    .index('by_contact', ['contactId'])
    .vectorIndex('by_embedding', { vectorField: 'embedding', dimensions: 1536, filterFields: ['caseId', 'category'] }),

  geminiNotesParsed: defineTable({
    rawNotes: v.optional(v.string()),
    parsed: v.optional(v.any()),
    createdAt: v.optional(v.number()),
    // Extended fields used by parseGeminiNotes.ts
    originalNoteId: v.optional(v.string()),
    claimNumber: v.optional(v.string()),
    vehicleYear: v.optional(v.number()),
    vehicleMake: v.optional(v.string()),
    vehicleModel: v.optional(v.string()),
    carrier: v.optional(v.string()),
    damageType: v.optional(v.string()),
    nextAction: v.optional(v.string()),
    confidence: v.optional(v.number()),
    parsedAt: v.optional(v.number()),
  }),
});
